"use strict";
/* =====================================================================
   SKY COMMANDER ACADEMY v2 — QUESTION BANK
   Learning-first: Kingdom Chronicles (Grade 4 history) is the core and
   is unlocked from the start. Jets / Army / Storm are reward worlds.

   Question types:
     mcq   {q, o:[4], a:idx, exp}
     order {q, items:[correct order], exp}          — tap in sequence
     match {q, pairs:[[left,right],...], exp}       — sequential pairing
     sort  {q, buckets:[A,B], items:[[text,0|1]], exp} — two-bucket sort
     map   {q, target:key, exp}                     — tap the tactical map
   Every question carries a `topic` tag for the Command Log.
   ===================================================================== */

const MAP_SPOTS = {
  kamboja:  {x:88,  y:34,  label:"Kamboja"},
  gandhara: {x:76,  y:60,  label:"Gandhara"},
  kuru:     {x:118, y:88,  label:"Kuru"},
  panchala: {x:141, y:96,  label:"Panchala"},
  surasena: {x:124, y:110, label:"Surasena"},
  matsya:   {x:106, y:126, label:"Matsya"},
  kosala:   {x:172, y:100, label:"Kosala"},
  kasi:     {x:184, y:113, label:"Kasi"},
  vajji:    {x:206, y:104, label:"Vajji"},
  magadha:  {x:214, y:122, label:"Magadha"},
  anga:     {x:238, y:128, label:"Anga"},
  vatsa:    {x:164, y:122, label:"Vatsa"},
  chedi:    {x:151, y:143, label:"Chedi"},
  avanti:   {x:116, y:162, label:"Avanti"},
  asmaka:   {x:136, y:226, label:"Asmaka"}
};

const WORLDS = [

  /* ================= 1. KINGDOM CHRONICLES I ================= */
  {
    id:"kingdom1",
    icon:"🏘️",
    name:"Kingdom Chronicles I",
    tagline:"RISE OF THE VILLAGES",
    desc:"Fly over the first villages! Canals, jhum fires, moving tribes and the experts who kept a village alive.",
    badge:{ico:"🏺",name:"Village Founder"},
    unlockStars:0,
    featured:true,
    scene:"river",
    questions:[
      {type:"mcq", topic:"Settling Down",
        q:"What finally made people STOP wandering and settle down in one place?",
        o:["They ran out of shoes","Farming and taming animals — crops and herds need you to stay put","Walking was banned","They lost their maps"],
        a:1,
        exp:"Once people learned <b>farming</b> and started <b>domesticating animals</b>, they had to stay near their fields and herds. Crops need watering, animals need care — so they built <b>permanent homes</b>. That's the moment villages were born!"},
      {type:"mcq", topic:"Settling Down",
        q:"A village's grain store is almost empty — the rains came late! What was the villagers' winning plan?",
        o:["Wait and hope for more rain","Move to the desert","Build a canal from the nearby stream and take turns watering the crops","Eat less food forever"],
        a:2,
        exp:"They didn't wait for the sky — they <b>built a canal from the stream</b> and <b>took turns watering</b>! Even the kids carried small pots of water. Teamwork saved the harvest. That's squadron thinking: everyone flies, everyone contributes!"},
      {type:"mcq", topic:"Settling Down",
        q:"Ploughs broke while digging the new canal! Which village expert makes stronger iron tips?",
        o:["The potter","The weaver","The trader","The blacksmith"],
        a:3,
        exp:"The <b>blacksmith</b> — the village's weapons engineer! And here's the genius part: the village called a meeting where <b>everyone shared what they could offer</b> — wood, metal or skill. A new system was born: everyone contributes, everyone benefits!"},
      {type:"match", topic:"Settling Down",
        q:"Village experts, report for duty! Match each specialist to what they make:",
        pairs:[
          ["Potter","Pots and jars to store food and water"],
          ["Blacksmith","Iron ploughs and swords"],
          ["Weaver","Cloth and blankets from cotton or wool"],
          ["Carpenter","Wooden furniture and tools"],
          ["Trader","Exchanges goods with other villages"]
        ],
        exp:"This is called <b>specialization</b> — instead of everyone doing everything, each expert mastered ONE job and the whole village became stronger. Farmers grew the food, and the potter, blacksmith, weaver, carpenter and trader kept the machine running!"},
      {type:"mcq", topic:"Tribes & Farming",
        q:"Why did the Bhil people move their camps every few months?",
        o:["To find fresh water and food as the seasons changed","Because tents get boring","To follow cricket matches","To avoid homework"],
        a:0,
        exp:"The <b>Bhils moved with nature's radar</b>: when a season dried up the water and food, the whole camp relocated. They also shifted for <b>safety and better weather</b>. Moving wasn't a holiday — it was mission-critical survival!"},
      {type:"mcq", topic:"Tribes & Farming",
        q:"In JHUM farming, why do farmers burn the plants before sowing seeds?",
        o:["To scare away birds","To keep warm in winter","Because the ash makes the soil rich, so crops grow better","To send smoke signals"],
        a:2,
        exp:"Fire mission with a purpose! The <b>ash acts like natural fertilizer</b>, making the soil rich so the next crop grows stronger. Jhum is also called 'slash-and-burn' farming, used by hill tribes for thousands of years."},
      {type:"mcq", topic:"Choosing a Home",
        q:"Your scouts must pick the BEST place for a new settlement. Which location wins rank #1?",
        o:["A hilltop","Near the Ganga river","A dense forest","The middle of a desert"],
        a:1,
        exp:"<b>Near the Ganga!</b> Water to drink and <b>fertile land for farming</b> are the most important things for survival — worth it even with some flood risk. Almost every great Indian city grew up next to a river!"},
      {type:"mcq", topic:"Choosing a Home",
        q:"What is the biggest PROBLEM with building your village on a hilltop?",
        o:["Too much fresh air","Too many eagles","It's too easy to defend","Water must be carried uphill every single day"],
        a:3,
        exp:"A hilltop is <b>safe from floods</b> and easy to defend — but imagine hauling every pot of water UP the hill, every day, forever. Exhausting! That's why hilltops ranked #2, not #1."},
      {type:"mcq", topic:"Choosing a Home",
        q:"A dense forest has wood and animals. Why is it still a hard place for a permanent village?",
        o:["Farming is very difficult among all the trees","Trees are scary at night","There's no phone signal","Forests are always cold"],
        a:0,
        exp:"Forests give you <b>wood and animals to hunt</b>, but clearing land to farm between giant trees and roots is brutally hard — and without farming, a big village can't feed itself long-term. Rank #3!"},
      {type:"mcq", topic:"Choosing a Home",
        q:"Why did rivers like the Ganga attract so many people?",
        o:["Rivers looked pretty in photos","Water + fertile land attracted people → settlements grew → kingdoms formed","Kings loved fishing","Boats were the only fun activity"],
        a:1,
        exp:"Lock in this chain reaction, cadet: <b>water + fertile land → people arrive → settlements grow → kingdoms form</b>. This one formula explains where almost every ancient kingdom on Earth appeared!"},
      {type:"mcq", topic:"Rivers & SDGs",
        q:"Which squad of Global Goals (SDGs) protects our rivers today?",
        o:["SDG 6, 13, 14 and 15","SDG 1 and 2 only","There are no goals for rivers","Only SDG 6"],
        a:0,
        exp:"Four goals fly in formation to guard rivers: <b>SDG 6</b> Clean Water & Sanitation, <b>SDG 13</b> Climate Action, <b>SDG 14</b> Life Below Water and <b>SDG 15</b> Life on Land. Together they keep water clean, cut pollution and protect river plants and animals!"},
      {type:"order", topic:"Timeline Skills",
        q:"Flight plan through history! Tap the growth stages in order, from FIRST to LAST:",
        items:["Native Settlers (3000–1500 BCE)","Early Villages (1500–800 BCE)","Janapadas (800–600 BCE)","Mahajanapadas (600–300 BCE)","Empires (300 BCE onwards)"],
        exp:"The full transformation chain: <b>Native Settlers</b> (huts, hunting, one leader) → <b>Early Villages</b> (farming, council of elders) → <b>Janapadas</b> (walls and a king) → <b>Mahajanapadas</b> (armies and trade) → <b>Empires</b> (many regions united under one ruler). Each stage is bigger and more organized than the last!"}
    ]
  },

  /* ================= 2. KINGDOM CHRONICLES II ================= */
  {
    id:"kingdom2",
    icon:"🏰",
    name:"Kingdom Chronicles II",
    tagline:"AGE OF EMPIRES",
    desc:"The 16 Mahajanapadas, mighty Magadha, republics vs kingdoms, and the empires that ruled India.",
    badge:{ico:"👑",name:"Empire Strategist"},
    unlockStars:0,
    featured:true,
    scene:"forts",
    questions:[
      {type:"mcq", topic:"Janapadas & Mahajanapadas",
        q:"When did the age of the Janapadas begin (roughly)?",
        o:["1969 CE","800–600 BCE","3500 BCE","Last Tuesday"],
        a:1,
        exp:"<b>Janapadas: 800–600 BCE</b>, and the <b>Mahajanapadas came next: 600–300 BCE</b>. Remember: with BCE, the numbers count DOWN as time moves forward — 800 BCE is older than 600 BCE!"},
      {type:"mcq", topic:"Janapadas & Mahajanapadas",
        q:"About how many people lived in a mighty Mahajanapada?",
        o:["Around 50","500 to 2,000","50,000 to 5,00,000 or even more","Nobody — they were empty"],
        a:2,
        exp:"A Mahajanapada could hold <b>50,000 to over 5,00,000 people</b> — while a little janapada had only 500–2,000! That's the difference between a village cricket team and a packed stadium."},
      {type:"mcq", topic:"Janapadas & Mahajanapadas",
        q:"What kind of army did a Mahajanapada command?",
        o:["A small militia of part-time fighters","No army at all","Only war elephants","A large professional army"],
        a:3,
        exp:"Mahajanapadas ran <b>large professional armies</b> — full-time trained soldiers, paid by taxes! Janapadas only had a <b>small militia</b>: farmers who grabbed weapons when trouble came. Professionals beat part-timers almost every time."},
      {type:"mcq", topic:"Janapadas & Mahajanapadas",
        q:"Out of MANY janapadas, why did only 16 earn the title 'MAHA' (great)?",
        o:["They had the tastiest food","They grew mightier in area, wealth, population and military power","Their names were longest","They were simply the oldest"],
        a:1,
        exp:"Those 16 leveled up in every stat: <b>area, wealth, population and military power</b>. They could <b>defend themselves, collect taxes and influence nearby regions</b> — that's what made them stand out as MAHA-janapadas!"},
      {type:"sort", topic:"Janapadas & Mahajanapadas",
        q:"Intel sorting drill! File each clue under the right era:",
        buckets:["JANAPADA","MAHAJANAPADA"],
        items:[
          ["Small militia",0],
          ["Large professional army",1],
          ["500–2,000 people",0],
          ["50,000–5,00,000+ people",1],
          ["Capital: small town",0],
          ["Capital: large city",1]
        ],
        exp:"See the pattern? A Mahajanapada is a janapada with <b>every dial turned up</b>: bigger population, bigger capital, and a professional army instead of a part-time militia."},
      {type:"sort", topic:"Janapadas & Mahajanapadas",
        q:"Second sorting run! Janapada or Mahajanapada?",
        buckets:["JANAPADA","MAHAJANAPADA"],
        items:[
          ["Basic agriculture",0],
          ["Advanced agriculture",1],
          ["Simple government",0],
          ["Complex government",1],
          ["Loose control of territory",0],
          ["Strong control of territory",1]
        ],
        exp:"Same upgrade pattern in farming and ruling: <b>basic → advanced agriculture</b>, <b>simple → complex government</b>, <b>loose → strong control</b>. More food + better organization = more power!"},
      {type:"mcq", topic:"Empires & Magadha",
        q:"Vajji and Malla were REPUBLICS. How did they make decisions?",
        o:["One king decided everything","Councils shared the decisions — fair, but slower","They flipped a coin","The tallest person decided"],
        a:1,
        exp:"In republics like <b>Vajji and Malla</b>, <b>councils shared decisions</b> — very fair, but slow, like a plane with ten pilots arguing over the controls. Kingdoms had ONE king and an army: fast and strong."},
      {type:"mcq", topic:"Empires & Magadha",
        q:"Why did KINGDOMS eventually beat the republics?",
        o:["They were faster, stronger and more united under one king","They had better weather","The republics just gave up","They had more festivals"],
        a:0,
        exp:"Kingdoms could decide and strike <b>fast</b>, act <b>united</b> under one commander, and field stronger armies. Over time they <b>conquered or absorbed the republics</b>. Fair-but-slow lost to fast-and-strong."},
      {type:"mcq", topic:"Empires & Magadha",
        q:"Why is MAGADHA the superstar of India's empire story?",
        o:["It had the world's first school","It never fought a single war","It was the most powerful Mahajanapada, conquered the others, and became the launchpad of the Mauryan Empire","It was the smallest and cutest"],
        a:2,
        exp:"<b>Magadha</b> was the final boss of the Mahajanapadas: it <b>conquered most of the others</b> through military strength and became the <b>foundation of the Mauryan Empire</b>. Rich land, iron mines, war elephants — the full power package!"},
      {type:"mcq", topic:"Empires & Magadha",
        q:"Which mighty empire rose right after the Mahajanapada age?",
        o:["The Gupta Empire","The Mauryan Empire","The Roman Empire","The British Empire"],
        a:1,
        exp:"The <b>Mauryan Empire (321–185 BCE)</b> came first — about 136 years of power! The <b>Gupta Empire (320–550 CE)</b> followed centuries later. Mauryan first, Gupta second — lock that order in!"},
      {type:"mcq", topic:"Empires & Magadha",
        q:"Who launched the Mauryan Empire from Magadha's capital city, Pataliputra?",
        o:["Chandragupta Maurya","Akbar","Bimbisara","Shivaji"],
        a:0,
        exp:"<b>Chandragupta Maurya</b> took command at <b>Pataliputra</b> (today's Patna!) and built India's first mega-empire. His grandson Ashoka later ruled almost all of India from the same base."},
      {type:"order", topic:"Timeline Skills",
        q:"Radar contact — 5 events incoming! Tap them from EARLIEST to LATEST:",
        items:["Invention of the Wheel (3500 BCE)","Simple Tools (3000 BCE)","Permanent Settlements (1500 BCE)","First Moon Landing (1969 CE)","Your First Day at School (2020 CE)"],
        exp:"Navigator's secret: <b>BCE years count DOWN</b> as time moves forward (3500 → 3000 → 1500), then <b>CE years count UP</b> (1969 → 2020). The wheel came before everything — no wheel, no supercars!"},
      {type:"order", topic:"Timeline Skills",
        q:"Line up India's power timeline, oldest first:",
        items:["Mahajanapadas (600–300 BCE)","Mauryan Empire (321–185 BCE)","Gupta Empire (320–550 CE)"],
        exp:"<b>Mahajanapadas → Mauryan → Gupta</b>. The Mahajanapadas were the training ground, the Mauryans built the first great empire from Magadha, and the Guptas ruled India's 'Golden Age' centuries later."},
      {type:"map", topic:"Map Skills",
        q:"TACTICAL MAP! Magadha rose in the EAST, along the lower Ganga river. Tap its sector!",
        target:"magadha",
        exp:"<b>Magadha</b> sat in the east where the Ganga made the land super-fertile — with iron mines and elephants nearby. Perfect base for an empire. Its capital Pataliputra is today's Patna, Bihar!"},
      {type:"map", topic:"Map Skills",
        q:"Gandhara guarded the far NORTH-WEST frontier — the gateway into India. Tap its sector!",
        target:"gandhara",
        exp:"<b>Gandhara</b> (around today's Peshawar–Taxila region) watched the north-west mountain passes. Traders, armies and ideas all entered India through this gate — whoever held Gandhara controlled the door!"},
      {type:"map", topic:"Map Skills",
        q:"Avanti held the WEST, commanding the great trade routes. Tap its sector!",
        target:"avanti",
        exp:"<b>Avanti</b> (capital: Ujjain) sat on the crossroads of India's busiest trade routes. Caravans of goods rolled through it — and taxing trade made Avanti rich and powerful!"},
      {type:"mcq", topic:"Map Skills",
        q:"Where were MOST of the 16 Mahajanapadas located?",
        o:["In the southern deserts","High in the Himalayas","Along the sea beaches","In the northern Indo-Gangetic Plains, around the Ganga"],
        a:3,
        exp:"Most Mahajanapadas clustered in the <b>Indo-Gangetic Plains of northern India</b>. Why? Say the chain with me: <b>water + fertile land + easy movement → people → settlements → kingdoms!</b>"}
    ]
  },

  /* ================= 3. TIME MACHINE (exam paper) ================= */
  {
    id:"time",
    icon:"⏳",
    name:"Operation Time Machine",
    tagline:"EXAM PAPER RUN 1",
    desc:"The exact practice-paper questions — early villages, chronology, janapada life. Fly it until it's perfect!",
    badge:{ico:"📜",name:"History Hawk"},
    unlockStars:0,
    scene:"dawn",
    questions:[
      {type:"mcq", topic:"History Basics",
        q:"The people who focused on basic survival and simple farming were…",
        o:["Early villages","Mahajanapadas","Janapadas","Native settlers"],
        a:0,
        exp:"<b>Early villages</b> were humanity's first base camps! People stopped wandering, set up camp near rivers, grew simple crops and focused on pure survival — food, shelter, safety. No kingdoms or armies yet, just brave families learning to farm."},
      {type:"mcq", topic:"History Basics",
        q:"If you were an early villager, what would you be doing for a living?",
        o:["Pottery","Making iron tools","Weaving","All of the above"],
        a:3,
        exp:"<b>All of the above!</b> Early villagers were multi-skilled, like a pilot who can also fix the engine. They shaped clay pots to store grain, wove cloth for clothes and hammered out tools. Every villager had a job in the squadron!"},
      {type:"mcq", topic:"Timeline Skills",
        q:"Putting events in the right order is called…",
        o:["Advancement","Linetime","Chronology","Detour"],
        a:2,
        exp:"<b>Chronology</b> — from 'chronos', the Greek word for TIME. Historians line up events like jets on a runway: first, next, last. Watch out for the decoy 'Linetime' — the real word is TIMEline, and arranging one is chronology!"},
      {type:"mcq", topic:"History Basics",
        q:"People of a Janapada live together in groups. Why is this helpful?",
        o:["To stop trade","To live without rules","To avoid working","For safety and cooperation"],
        a:3,
        exp:"<b>Safety and cooperation</b> — squadrons fly in formation for the exact same reason! Together, people could guard each other from danger, share huge jobs like farming and building, and swap skills. Teamwork = survival."},
      {type:"mcq", topic:"Money & Banking",
        q:"Assertion (A): Barter is the exchange of goods without money.\nReason (R): People use debit cards in the barter system.",
        o:["Both A and R are true, and R explains A","A and R are true, but R does not explain A","A is true, but R is false","A is false, but R is true"],
        a:2,
        exp:"A is <b>TRUE</b> — barter means swapping goods directly, like trading rice for a clay pot. R is <b>FALSE</b> — debit cards in barter times?! Money didn't even exist yet. Cards are modern tech, thousands of years after barter. So: A true, R false!"},
      {type:"mcq", topic:"History Basics",
        q:"If you could advise a Mahajanapada ruler, what would be the best suggestion?",
        o:["Close all markets","Improve farming, trade and security","Reduce food production","Stop building roads"],
        a:1,
        exp:"A smart ruler thinks like a squadron leader: keep everyone fed (<b>farming</b>), keep goods and money flowing (<b>trade</b>), and defend the base (<b>security</b>). Kingdoms that mastered all three — like Magadha — became superpowers!"},
      {type:"mcq", topic:"History Basics",
        q:"How did life change when early settlers became villagers?",
        o:["They stopped eating food","They built permanent homes, started farming and kept animals","They started flying jets","Nothing changed at all"],
        a:1,
        exp:"Three mega-upgrades, cadet: <b>1)</b> permanent homes instead of wandering, <b>2)</b> growing their own food by farming instead of only hunting and gathering, <b>3)</b> taming animals like cows, goats and dogs. That's how villages — and later cities — took off!"},
      {type:"order", topic:"Timeline Skills",
        q:"Chronology drill! Tap these in the order they happened:",
        items:["Native settlers build the first huts","Early villages learn farming","Janapadas raise walls and kings","Mahajanapadas build armies and trade"],
        exp:"Huts → farms → walls & kings → armies & trade. Each stage stacks on the one before it, like a jet climbing altitude bands. This chain IS the story of ancient India!"},
      {type:"mcq", topic:"History Basics",
        q:"You're a member of the Bhil tribe. Why might your family move from one camp to another?",
        o:["To find food, water and grazing land as seasons change","Because tents get boring","To watch television","To avoid school"],
        a:0,
        exp:"Tribes like the <b>Bhils moved with nature's radar</b>! When a season made food, water or grass for their animals run low, the whole camp relocated to a better spot. Moving wasn't a holiday — it was a survival strategy."}
    ]
  },

  /* ================= 4. GOLD RUPEE (exam paper) ================= */
  {
    id:"money",
    icon:"💰",
    name:"Operation Gold Rupee",
    tagline:"EXAM PAPER RUN 2",
    desc:"Crack the code of money — from ancient barter swaps to lightning-fast digital payments.",
    badge:{ico:"🪙",name:"Treasure Tactician"},
    unlockStars:0,
    scene:"dusk",
    questions:[
      {type:"mcq", topic:"Money & Banking",
        q:"What is barter?",
        o:["Buying things with coins","Exchanging goods without using money","Shopping online","Keeping money in a bank"],
        a:1,
        exp:"<b>Barter = swap!</b> Long before coins and notes, people traded things directly — a sack of rice for a clay pot, a goat for cloth. No money involved, just deal-making skills!"},
      {type:"mcq", topic:"Money & Banking",
        q:"Aman has rice, Raman has a clay pot. Why might their barter exchange FAIL?",
        o:["Rice and pots are illegal to trade","Raman may not want rice, and the goods may not be of equal value","Aman's rice is too tasty","They don't have a shopping app"],
        a:1,
        exp:"Barter has two famous glitches: <b>1)</b> the other person must actually WANT what you have — maybe Raman doesn't need rice! <b>2)</b> the swap must feel FAIR — is one pot really worth a whole sack of rice? These problems are exactly why humans invented money!"},
      {type:"mcq", topic:"Money & Banking",
        q:"The Indian Rupee symbol ₹ was designed by ______ in ______.",
        o:["D Udaya Kumar, 2010","D Kumar, 2015","Kumar, 2012","Yuday Kumar, 2010"],
        a:0,
        exp:"Target locked: <b>D Udaya Kumar</b> designed the ₹ symbol in <b>2010</b>. It cleverly blends the Devanagari letter 'र' with the Roman 'R', and its two horizontal lines stand for the Indian flag. A symbol as iconic as the Air Force roundel!"},
      {type:"mcq", topic:"Money & Banking",
        q:"Meera's family deposits old notes in their bank account. What is the main benefit?",
        o:["The bank keeps the money forever","The notes become toys","The money is safe and can be used later","The family gets free gifts"],
        a:2,
        exp:"A bank is a <b>high-security hangar for your money</b>! Deposited money is protected from loss and theft, it can even grow a little (that's called interest), and it's ready for launch whenever you need it."},
      {type:"mcq", topic:"Money & Banking",
        q:"What are digital payments?",
        o:["Paying with paper letters","Drawing pictures of money","Trading goods for goods","Paying money electronically using phones, cards or computers"],
        a:3,
        exp:"<b>Digital payments</b> move money electronically — no cash needed! With a phone, card or computer, money zooms from one bank account to another in seconds. It's money travelling at jet speed!"},
      {type:"mcq", topic:"Money & Banking",
        q:"Which of these are types of digital payments?",
        o:["UPI apps and debit/credit cards","Giving someone a cow","Writing a nice poem","Handing over seashells"],
        a:0,
        exp:"<b>UPI</b> (apps like Google Pay, PhonePe, Paytm) fires money phone-to-phone instantly, and <b>debit/credit cards</b> let you pay with a tap or swipe. Net banking and mobile wallets are digital payments too!"},
      {type:"order", topic:"Money & Banking",
        q:"The story of money! Tap the stages in order, oldest first:",
        items:["Barter — swapping goods for goods","Coins and paper notes","Debit and credit cards","UPI — instant phone payments"],
        exp:"Money kept upgrading like a fighter jet: <b>barter</b> (slow, needs matching wants) → <b>coins & notes</b> (easy to carry and count) → <b>cards</b> (tap and pay) → <b>UPI</b> (money at the speed of light). Each stage fixed the last one's problems!"}
    ]
  },

  /* ================= 5. SKY GUARDIANS (reward) ================= */
  {
    id:"jets",
    icon:"✈️",
    name:"Operation Sky Guardians",
    tagline:"REWARD WORLD — 3★ TO UNLOCK",
    desc:"Tejas, Rafale, Sukhoi — how well do you know the guardians of Indian skies?",
    badge:{ico:"🛩️",name:"Fighter Ace"},
    unlockStars:3,
    scene:"highalt",
    questions:[
      {type:"mcq", topic:"Fighter Jets",
        q:"Which fighter jet is designed and built in India?",
        o:["Rafale","F-16","Tejas","MiG-21"],
        a:2,
        exp:"The <b>HAL Tejas</b> is India's own home-grown fighter — designed and built right here! 'Tejas' is Sanskrit for <b>radiance</b>. It's small, super-agile and one of the lightest supersonic fighters on the planet. 🇮🇳"},
      {type:"mcq", topic:"Fighter Jets",
        q:"India's Rafale fighter jets come from which country?",
        o:["Russia","France","USA","Japan"],
        a:1,
        exp:"The <b>Rafale</b> roars in from <b>France</b>, built by Dassault Aviation. 'Rafale' means 'gust of wind' — and with twin engines and deadly precision, it's one of the most feared jets in the sky!"},
      {type:"mcq", topic:"Fighter Jets",
        q:"Which big twin-engine fighter, built with Russia, forms the backbone of the Indian Air Force?",
        o:["Sukhoi Su-30MKI","Mirage 2000","Tejas","Cessna"],
        a:0,
        exp:"The mighty <b>Sukhoi Su-30MKI</b>! It's big, carries two pilots, and can pull jaw-dropping stunts like the 'Cobra' — rearing its nose up mid-flight like a striking snake. The IAF flies more than 250 of them!"},
      {type:"mcq", topic:"Fighter Jets",
        q:"What happens when a jet flies FASTER than the speed of sound?",
        o:["It travels back in time","It creates a sonic boom","Its wings fall off","It becomes invisible"],
        a:1,
        exp:"<b>BOOM!</b> Crossing the speed of sound (about 1,235 km/h — called Mach 1) squashes the air into a shockwave, and people below hear a thunder-like <b>sonic boom</b>. Fighter pilots call it 'going supersonic'!"},
      {type:"mcq", topic:"Fighter Jets",
        q:"What is the motto of the Indian Air Force?",
        o:["Fly Fast, Fly Far","Touch the Sky with Glory","Kings of the Clouds","Speed is Life"],
        a:1,
        exp:"<b>'Touch the Sky with Glory'</b> — from the Sanskrit 'Nabhah Sprisham Deeptam', words taken from the Bhagavad Gita. Every IAF pilot flies with that motto burning in their heart!"},
      {type:"mcq", topic:"Fighter Jets",
        q:"Fighter pilots wear a special suit for sharp, high-speed turns. What is it called?",
        o:["A space suit","A G-suit","A raincoat","A turbo jacket"],
        a:1,
        exp:"The <b>G-suit</b>! In a hard turn, gravity multiplies (pilots call it 'pulling Gs') and blood gets yanked toward your feet. The G-suit squeezes the legs like a python hug so blood keeps reaching the brain and the pilot stays sharp!"},
      {type:"mcq", topic:"Fighter Jets",
        q:"What is the name of the IAF's famous aerobatic display team?",
        o:["Thunder Tigers","Sky Dancers","Surya Kiran","Falcon Five"],
        a:2,
        exp:"<b>Surya Kiran</b> — meaning 'Sun Rays'! Nine orange-and-white Hawk jets flying wingtip-to-wingtip, painting loops, hearts and arrows in the sky. Precision flying at its absolute coolest."}
    ]
  },

  /* ================= 6. BRAVE HEARTS (reward) ================= */
  {
    id:"army",
    icon:"🪖",
    name:"Operation Brave Hearts",
    tagline:"REWARD WORLD — 6★ TO UNLOCK",
    desc:"Salute the Indian Army! Medals, mountains, tanks and the heroes who guard our nation.",
    badge:{ico:"🎖️",name:"Iron Guardian"},
    unlockStars:6,
    scene:"mountain",
    questions:[
      {type:"mcq", topic:"Indian Army",
        q:"The Indian Army guards the HIGHEST battlefield in the world. What is it called?",
        o:["Mount Everest","Siachen Glacier","Thar Desert","Kanchenjunga"],
        a:1,
        exp:"The <b>Siachen Glacier</b> — around 6,000 metres up in the Karakoram mountains, where temperatures crash below −50°C! Indian soldiers guard it day and night. It takes unbelievable courage just to breathe up there."},
      {type:"mcq", topic:"Indian Army",
        q:"What is India's highest award for bravery in war?",
        o:["Param Vir Chakra","Bharat Ratna","Gold Star Medal","Arjuna Award"],
        a:0,
        exp:"The <b>Param Vir Chakra</b> — 'Wheel of the Ultimate Brave'. It's given for the most extraordinary courage in battle, often to heroes who gave their lives for the nation. The rarest and most respected medal in India."},
      {type:"mcq", topic:"Indian Army",
        q:"When is Indian Army Day celebrated?",
        o:["26 January","15 August","15 January","2 October"],
        a:2,
        exp:"<b>15 January!</b> On that day in 1949, Field Marshal K. M. Cariappa became the first INDIAN to command the Indian Army. Every year the Army marks it with parades and shows of skill."},
      {type:"mcq", topic:"Indian Army",
        q:"Which main battle tank was designed in India?",
        o:["Tiger","Abrams","T-90","Arjun"],
        a:3,
        exp:"The <b>Arjun</b> — India's own main battle tank, named after the legendary archer from the Mahabharata! It weighs about 68 tonnes (like 10 elephants) and its cannon can hit targets kilometres away."},
      {type:"mcq", topic:"Indian Army",
        q:"What is the motto of the Indian Army?",
        o:["Attack First","Service Before Self","Strength and Speed","Never Sleep"],
        a:1,
        exp:"<b>'Service Before Self'</b> — the nation comes first, always. That's why soldiers stand guard in freezing mountains and burning deserts while we sleep safely at home. Salute! 🫡"},
      {type:"mcq", topic:"Indian Army",
        q:"On Republic Day, the Army's grand parade marches down which famous road in Delhi?",
        o:["Marine Drive","Kartavya Path","MG Road","Ring Road"],
        a:1,
        exp:"<b>Kartavya Path</b> (earlier called Rajpath)! Every 26 January, tanks rumble, soldiers march in perfect formation, and fighter jets scream overhead in salute. It's India's mightiest show of pride."}
    ]
  },

  /* ================= 7. TURBO STORM (reward) ================= */
  {
    id:"turbo",
    icon:"🌪️",
    name:"Operation Turbo Storm",
    tagline:"REWARD WORLD — 9★ TO UNLOCK",
    desc:"Final frontier: spinning tornados, screaming supercars and ninja-level origami!",
    badge:{ico:"🏎️",name:"Storm Racer"},
    unlockStars:9,
    scene:"storm",
    questions:[
      {type:"mcq", topic:"Storms & Speed",
        q:"What shape does a tornado make as it touches the ground?",
        o:["A perfect cube","A spinning funnel cloud","A flat pancake","A zigzag lightning bolt"],
        a:1,
        exp:"A <b>spinning funnel cloud</b> — like a monstrous grey drill from the sky! Inside, winds can whirl at over 300 km/h, faster than a Formula 1 car at full throttle."},
      {type:"mcq", topic:"Storms & Speed",
        q:"Which scale do scientists use to measure a tornado's power?",
        o:["The Richter scale","The Celsius scale","The Fujita (EF) scale","The Mach scale"],
        a:2,
        exp:"The <b>Fujita scale</b> (today the 'EF scale') rates tornados from EF0 (weak) to EF5 (city-flattening monster). The Richter scale is a decoy — that one measures earthquakes!"},
      {type:"mcq", topic:"Storms & Speed",
        q:"A tornado warning sounds! Where is the SAFEST place to go?",
        o:["Under a big tree","Next to a window to watch","In a car on the highway","A basement or a small inner room away from windows"],
        a:3,
        exp:"Get LOW and get INSIDE: a <b>basement or a small inner room away from windows</b> is your bunker. Flying glass and debris are a tornado's main weapons — windows are the danger zone, not the viewing gallery!"},
      {type:"mcq", topic:"Storms & Speed",
        q:"Which company builds the Chiron, one of the fastest supercars ever (over 400 km/h)?",
        o:["Bugatti","Maruti","Tata","Toyota"],
        a:0,
        exp:"<b>Bugatti!</b> The Chiron's engine has 16 cylinders and about 1,500 horsepower — roughly the power of 15 normal cars glued together. At top speed it covers 100 metres in less than a second!"},
      {type:"mcq", topic:"Storms & Speed",
        q:"Why are supercars built so low and smooth-shaped?",
        o:["To fit in small garages","To look scary at night","So air flows over them smoothly — just like a jet (aerodynamics!)","To save paint"],
        a:2,
        exp:"<b>Aerodynamics</b> — the same science that makes fighter jets fast! A low, smooth body lets air slide over the car instead of pushing against it, and spoilers press it onto the road for grip. Supercars are basically jets that forgot their wings."},
      {type:"mcq", topic:"Storms & Speed",
        q:"The art of paper folding, 'origami', comes from which country?",
        o:["Brazil","Japan","Egypt","Australia"],
        a:1,
        exp:"<b>Japan!</b> 'Ori' means fold and 'kami' means paper. The most famous fold is the paper crane — legend says folding 1,000 cranes grants a wish. Ancient art, ninja-level patience!"},
      {type:"mcq", topic:"Storms & Speed",
        q:"Why does a paper plane with sharp, crisp folds fly farther?",
        o:["Sharp folds make it heavier","Crisp folds cut through the air smoothly, giving more lift and less drag","The paper gets angry","Sharp folds make it invisible"],
        a:1,
        exp:"<b>Crisp folds = clean aerodynamics!</b> Sharp, even folds keep the wings balanced and let air flow smoothly, giving more lift and less drag. Sloppy folds make air tumble and the plane crash-dive. Real jet engineers obsess over the same thing!"}
    ]
  }
];

const RANKS = [
  {min:0,    ico:"🧢", name:"CADET"},
  {min:1000, ico:"🎖️", name:"FLYING OFFICER"},
  {min:2500, ico:"🥈", name:"SQUADRON LEADER"},
  {min:4500, ico:"🥇", name:"WING COMMANDER"},
  {min:7000, ico:"👑", name:"AIR MARSHAL LEGEND"}
];

const PRAISE = ["DIRECT HIT! 🎯","ROGER THAT, ACE!","TARGET DESTROYED! 💥","AFTERBURNERS ON! 🔥","MISSILE LOCK — PERFECT! 🚀","OUTSTANDING FLYING! ⭐"];
const OOPS   = ["MISSED — RECALIBRATE! 🧭","EJECT! WRONG TARGET! 😅","TURBULENCE! TRY AGAIN SOON 🌀","NEGATIVE, CADET — DEBRIEF TIME 📡"];
const QUOTES3 = "FLAWLESS VICTORY, ACE! Every single target hit on the FIRST pass. The whole squadron is talking about you! 🏆";
const QUOTES2 = "Mission mastered, Commander! A couple of targets needed a second pass — but you locked them ALL in. That's how pilots learn!";
const QUOTES1 = "Mission mastered! It took a few extra passes, but you never gave up — and now you KNOW this stuff. Fly it again for 3 stars!";

const MAYDAY_CALLS = [
  {title:"MAYDAY! ENGINE FIRE!", sub:"Answer the emergency question to trigger the fire suppression system!"},
  {title:"MAYDAY! BIRD STRIKE!", sub:"Quick — answer correctly to restart the engine!"},
  {title:"MAYDAY! FUEL LEAK!", sub:"Seal the leak by locking in the right answer!"},
  {title:"MAYDAY! RADAR JAMMED!", sub:"Reboot the radar with a correct answer, fast!"}
];
